# lists can be assigned too 
myList = [1,2,3,4,5]
myList2 = myList

heterogeneous = [true, false, [1]] # parser does not prohibit heterogeneous lists

myList3 = getList(3, 1, true)
isTrue = false
myGpa = 2.0 # just an example to show floats can be assigned to variables

# this is a comment

# assigning string literals with non-ascii characters
myFunkyString = "this is a string with non-ascii characters: 你好€ÒÓ˝”"
