name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install ocaml && sudo apt install ocamlbuild

    - name: Compile sPool toplevel
      run: make -j -C src
      
    - name: Run lexer and scanner tests
      run: make test -j -C src
