name: sPool Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compiler-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install ocaml && sudo apt install ocamlbuild

    - name: Compile sPool toplevel
      run: make -j -C src
      
    - name: Run lexer and scanner tests
      run: make testparser -j -C src
    
    - name: Run semantic checker tests
      run: make testsemant -j -C src
