name: sPool Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compiler-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - uses: awalsh128/cache-apt-pkgs-action@latest # cache the packages on subsequent builds
    #   with:
    #     packages: ocaml llvm opam ocamlbuild m4 cmake

    - name: Install dependencies
      run: |
           sudo apt install opam ocaml ocamlbuild llvm m4 cmake

    - name: Compile sPool toplevel
      run: |
           opam init --yes
           opam install llvm --yes
           eval $(opam config env) && rm -f *.o
           make -j -C src
      
    - name: Run lexer and scanner tests
      run: make testparser -j -C src
    
    - name: Run codegen tests
      run: make testcodegen -j -C src
