name: sPool Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compiler-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest # cache the packages on subsequent builds
      with:
        packages: ocaml llvm opam ocamlbuild m4 cmake

    - name: Install dependencies
      run: |
           opam init --yes
           opam install llvm --yes

    - name: Compile sPool toplevel
      run: |
           eval $(opam config env)
           make -j -C src
      
    - name: Run lexer and scanner tests
      run: make testparser -j -C src
    
    - name: Run semantic checker tests
      run: make testsemant -j -C src
